//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoonBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amid the hum of machinery, Dante carefully adjusted a tool in his hand. \&quot;Hand me that micro-welder, will you?&quot; he asked a colleague. After a brief pause, he continued, \&quot;This place, this workshop—it&apos;s where we turn challenges into opportunities. Every problem we face here is just another puzzle to solve.&quot;.
        /// </summary>
        internal static string dialog_Dante {
            get {
                return ResourceManager.GetString("dialog_Dante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking out from one of the open windows, Lira&apos;s eyes were lost in the vastness of the lunar terrain. &quot;You know,&quot; she started, pulling the privacy screen around her bed down slightly, &quot;I never get tired of this view. Makes you feel so small yet a part of something much larger.&quot;.
        /// </summary>
        internal static string dialog_Lira {
            get {
                return ResourceManager.GetString("dialog_Lira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external comms crackled to life as Noelle began her transmission. &quot;Noelle here. I&apos;m outside MoonBase Theta. The expanse is quiet today.&quot; There&apos;s a moment of contemplative silence before she added, &quot;Being out here, in this hardsuit, you&apos;re reminded of the fragility of it all. Yet look at what we&apos;ve built..
        /// </summary>
        internal static string dialog_Noelle {
            get {
                return ResourceManager.GetString("dialog_Noelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipping on a mug filled with a steaming, nutrient-rich beverage, Rajan gestured towards the panoramic window showcasing the lunar Earthrise. &quot;Every time I sit here and have a meal, I&apos;m reminded of the first time I saw that view. Magical, isn&apos;t it? Makes this freeze-dried food taste just a little bit better.&quot;.
        /// </summary>
        internal static string dialog_Rajan {
            get {
                return ResourceManager.GetString("dialog_Rajan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The canteen at MoonBase Theta is a welcoming oasis of camaraderie in the lunar expanse. Its sleek, minimalist design features polished metal surfaces, ergonomic seating, and large, panoramic windows that offer breathtaking views of the lunar landscape. The soft hum of ventilation systems mingles with the friendly chatter of astronauts, creating a cozy atmosphere as they gather to enjoy delicious, space-age meals and unwind from their lunar duties. It&apos;s a place where astronauts come together, forging bonds o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DininghallText {
            get {
                return ResourceManager.GetString("DininghallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining Hall.
        /// </summary>
        internal static string DininghallTitle {
            get {
                return ResourceManager.GetString("DininghallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonBase Theta is a remarkable lunar outpost, constructed from a striking array of prefabricated modules and equipment. Its exterior is a testament to human ingenuity and adaptability in the harsh lunar environment. The base&apos;s metallic skin glistens in the soft lunar sunlight, its modular design resembling a futuristic puzzle of interconnected components. Solar panels stretch across the surface, capturing precious sunlight to power the base&apos;s vital systems, while a series of airlocks and sealed hatches punc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExteriorText {
            get {
                return ResourceManager.GetString("ExteriorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ExteriorTitle {
            get {
                return ResourceManager.GetString("ExteriorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The habitat is a cozy and efficient living space, featuring open windows that allow natural light to flood in, offering breathtaking views of the surrounding lunar landscape. Its ingenious design incorporates stacked, in-wall beds equipped with fold-down privacy screens, optimizing the limited space without sacrificing comfort and personal space for the inhabitants. The privacy screens provide a sense of personal retreat while preserving the sense of openness within the habitat, creating a harmonious balanc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HabitatText {
            get {
                return ResourceManager.GetString("HabitatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitat.
        /// </summary>
        internal static string HabitatTitle {
            get {
                return ResourceManager.GetString("HabitatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_Dante {
            get {
                object obj = ResourceManager.GetObject("img_Dante", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_dininghall {
            get {
                object obj = ResourceManager.GetObject("img_dininghall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_exterior {
            get {
                object obj = ResourceManager.GetObject("img_exterior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_habitat {
            get {
                object obj = ResourceManager.GetObject("img_habitat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_Lira {
            get {
                object obj = ResourceManager.GetObject("img_Lira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_Noelle {
            get {
                object obj = ResourceManager.GetObject("img_Noelle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_Rajan {
            get {
                object obj = ResourceManager.GetObject("img_Rajan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_workshop {
            get {
                object obj = ResourceManager.GetObject("img_workshop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workshop at MoonBase Theta is a bustling hub of innovation and problem-solving. Its compact, utilitarian design optimizes every inch of space, housing an array of state-of-the-art tools and equipment. Here, astronauts and scientists collaborate to fabricate, repair, and innovate, working tirelessly to overcome the unique challenges posed by the lunar environment. The soft hum of machinery and the scent of metalwork permeate the air, underscoring the workshop&apos;s vital role in sustaining life and advancing [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkshopText {
            get {
                return ResourceManager.GetString("WorkshopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string WorkshopTitle {
            get {
                return ResourceManager.GetString("WorkshopTitle", resourceCulture);
            }
        }
    }
}
